# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-10 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axf_foodtype',
            name='childtypenames',
            field=models.CharField(max_length=128),
        ),
    ]
