# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-10 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0003_axf_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axf_goods',
            name='childcidname',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='axf_goods',
            name='productname',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='axf_goods',
            name='specifics',
            field=models.CharField(max_length=64),
        ),
    ]
