# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-16 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MarketApp', '0004_auto_20191010_1347'),
        ('UserApp', '0002_axf_user_u_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Axf_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_time', models.DateTimeField(auto_now_add=True)),
                ('o_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.Axf_user')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='Axf_order_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('og_goods_num', models.IntegerField()),
                ('og_price', models.FloatField()),
                ('og_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MarketApp.Axf_goods')),
                ('og_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderApp.Axf_order')),
            ],
            options={
                'db_table': 'axf_order_goods',
            },
        ),
    ]
