# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-16 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='axf_order',
            old_name='o_user_id',
            new_name='o_user',
        ),
    ]
