# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-10-12 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='axf_user',
            name='u_token',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
